### ISSUE TITLE
Deep link [Question]

### ISSUE THREAD

**Issue by garsdle** [Dimillian/RedditOS#10]
Amazing project!

I'm curious how you would implement deep linking into this? Let's say you open a link to a specific post.

**Comment by Dimillian** [comment]
Right now the app handle custom `redditos://` url for oauth. And SwiftUI support a `onOpenIRL` modifier that you can plug on any view. So it would just be a matter of catching a `redditos://links/:id` somewhere in the view and triggering a NavigationLink programatically

**Comment by garsdle** [comment]
Awesome. Thanks!
