### ISSUE TITLE
[UI] Subreddit text color in feed has same color as background

### ISSUE THREAD

**Issue by ThatIsAPseudo** [Dimillian/RedditOS#17]
The subreddit text is white like the background, si it's unvisible unless you select the post, which changes the backgound color to orange.

**Comment by Dimillian** [comment]
Thanks, I need to do some testing in light mode as I mainly use it in dark mode.

**Comment by sarthaktexas** [comment]
I'm just commenting cause this looks like a good PR for me to try to do.

**Comment by Dimillian** [comment]
I've fixed it sorry :)
