### ISSUE TITLE
Does this work for macOS catalina?

### ISSUE THREAD

**Issue by sealvessel** [Dimillian/RedditOS#27]
I have tried changing the deployment target but it still says the module "Backend" upon building requires mac os 10.16.

**Comment by Person2099** [comment]
Unfortunately this application was built for Swift UI on macOS 11, Big Sur, and won't work on any previous software.

**Comment by navi-brunch** [comment]
please we want Catalina support

**Comment by Dimillian** [comment]
You don't get it, ever.

**Comment by MaximBazarov** [comment]
> please we want Catalina support

form readme:
>You'll need Xcode 12 and macOS Big Sur 12 to build & run the app. This is quite bleeding edge, the performances are not quite there yet as SwiftUI higher order components on macOS (like List and NavigationView) are not really very smooth yet. I hope it'll improve during Big Sur update cycle and I exept a big boost with SwiftUI 3 next summer. (One can hope)


So this is just impossible.
