### ISSUE TITLE
Slow and buggy behavior is very slow macOS Big Sur

### ISSUE THREAD

**Issue by ow8m8laune** [Dimillian/RedditOS#29]
I've just installed the software but I'm getting very slow behavior from it. Clicking on Any post takes way to long to show content. And my 3k $ mbp should not have any issues with that one.

**Comment by Dimillian** [comment]
SwiftUI is slow on macOS. This is reported to Apple and improved quite a bit in Big Sur updates. But there is still a lot of works. Hope SwiftUI 3 this summer will be much faster on macOS! Nothing much I can do on my side for now.

**Comment by ow8m8laune** [comment]
> SwiftUI is slow on macOS. This is reported to Apple and improved quite a bit in Big Sur updates. But there is still a lot of works. Hope SwiftUI 3 this summer will be much faster on macOS! Nothing much I can do on my side for now.

Ty alot for your response! Didn't know that problem was on apples side.. Bummer. Alright. Ty alot! I keep looking forward!
