### ISSUE TITLE
Please put 0.4 released app into "Assets"

### ISSUE THREAD

**Issue by singularitti** [Dimillian/RedditOS#30]
As you see, the current position is here
![image](https://user-images.githubusercontent.com/25192197/118311245-a41b4000-b4bd-11eb-8b44-a5a5f5f317ec.png)

while in previous releases they were in "Assets"
![image](https://user-images.githubusercontent.com/25192197/118311346-ca40e000-b4bd-11eb-8281-6c965aa048c9.png)

In the current case, I cannot push my edits to the [homebrew cask](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/curiosity.rb) because of the download link is not right. I don't want to change that link just for this release. Could you please move the app's position? Thank you!

**Comment by Dimillian** [comment]
Fixed :)

**Comment by singularitti** [comment]
OK!
