### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by zenminimalist** [Dimillian/RedditOS#67]
I really love where this client is going. Any plans continuing this "Apollo-esk" app?

**Comment by Dimillian** [comment]
Even if I was motivated to continue it, Reddit making their API prohibitively expensive completely killed the mood for making a client. So yes it's pretty much dead :(

**Comment by zenminimalist** [comment]
Wait, you don't have millions to finance the API costs as an open source project? 🤣

Jokes aside. That's what I assumed, but didn't want to hear, but totally understandable 😞 The whole sh*t show of what the Reddit CEO pulled is just said. The platform could've continued to be great. 

Thanks anyway for creating the app! I'll use it as long as it works...

**Comment by aljustiet** [comment]
> Even if I was motivated to continue it, Reddit making their API prohibitively expensive completely killed the mood for making a client. So yes it's pretty much dead :(

😭
