### ISSUE TITLE
Build Error: "AVAudioSession is unavailable on macOS"

### ISSUE THREAD

**Issue by samcat116** [Dimillian/RedditOS#9]
OS: macOS 11b3
Xcode version 12 beta 3 (12A8169g)
Seems to be tied to AVKit the `VideoPlayer` SwiftUI view. 
<img width="1512" alt="Screen Shot 2020-07-25 at 12 35 27 PM" src="https://user-images.githubusercontent.com/11448286/88461651-5290be80-ce73-11ea-9808-4474482de8f1.png">

Detailed error messages: 

`/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/_AVKit_SwiftUI.framework/Modules/_AVKit_SwiftUI.swiftmodule/x86_64-apple-macos.swiftinterface:4:8: Failed to build module 'AVFoundation' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.2.22.2 clang-1200.0.25.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.22.4 clang-1200.0.25.1)'`

The above seems like it is a minor Swift compiler mismatch, but interested to see if others have seen this. If this is an Swift bug I will file Feedback.

Steps to reproduce: 
1. Clone repository
2. Update Development team
3. Attempt to Build

**Comment by Dimillian** [comment]
In beta 3 you'll have to comment some interface in .swiftinterface AVFoundation system framework. 

https://twitter.com/dimillian/status/1286265975969587200?s=21

**Comment by samcat116** [comment]
That did the trick, thanks!
